version: '3.8'

services:
  app:
    build:
      context: ./bankcards
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=redis

      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
      - SECURITY_ENC_KEY=${SECURITY_ENC_KEY}
      - SECURITY_JWT_EXPIRATION=${SECURITY_JWT_EXPIRATION}
      - TEST_USERNAME=${TEST_USERNAME}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:latest
    command: ["postgres", "-c", "port=5432"]
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - bankcards_pg:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank -d bankcards" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 60 1 --loglevel warning

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  bankcards_pg:
