services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5433:5432"
    volumes:
      - bankcards_pg:/var/lib/postgresql/data
volumes:
  bankcards_pg:
