version: '3.8'

services:
  db:
    image: postgres:latest
    command: ["postgres", "-c", "port=5432"] # Внутри контейнера лучше оставить 5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432" # Снаружи будет тот порт, что в .env
    volumes:
      - bankcards_pg:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank -d bankcards" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 60 1 --loglevel warning

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  bankcards_pg:
